=== usnistgov/cds-base/cds-base/cds-base-service/src/main/resources/schema/vaccine_matcher.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://fits.nist.gov/vaccine_matcher/" targetNamespace="http://fits.nist.gov/vaccine_matcher/">

    <element name="VaccineMatcher" type="tns:VaccineMatcherType"></element>
    
    <complexType name="VaccineMatcherType">
    	<sequence>
    		<element name="VaccineMapping" type="tns:VaccineMappingType"></element>
    	</sequence>
    	<attribute name="matchSameGroup" type="boolean"></attribute>
    </complexType>

    <complexType name="VaccineMappingType">
    	<sequence>
    		<element maxOccurs="unbounded" minOccurs="0" name="EquivalentMatch" type="tns:EquivalentMatchType"></element>
    	</sequence>
    </complexType>

    <complexType name="EquivalentMatchType">

    	<sequence>
    		<choice maxOccurs="unbounded" minOccurs="1"><element name="Group" type="tns:GroupType"></element><element name="CVX" type="tns:CVXType"></element></choice>
    	</sequence>
    </complexType>

    <complexType name="GroupType">
    	<attribute name="code" type="string"></attribute>
    	<attribute name="value" type="string"></attribute>
    </complexType>

    <complexType name="CVXType">
    	<attribute name="code" type="string"></attribute>
    	<attribute name="value" type="string"></attribute>
    </complexType>
    
</schema>

=== usnistgov/cds-base/cds-base/cds-base-service/src/main/resources/cdc/groups-mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:VaccineMatcher matchSameGroups="true" xmlns:tns="http://fits.nist.gov/vaccine_matcher/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://fits.nist.gov/vaccine_matcher/ vaccine_matcher.xsd ">
	<VaccineMapping>
	
		<EquivalentMatch>
			<Group code="115" value="TDAP"/>
			<Group code="139" value="Td"/>
			<Group code="107" value="DTAP"/>
		</EquivalentMatch>
		
		<EquivalentMatch>
			<Group code="152" value="PneumoPCV"/>
			<Group code="33" value="PneumoPPV"/>
			<CVX code="109" value="Pneumococcal, Unspecified formulation"/>
		</EquivalentMatch>
		
	</VaccineMapping>
</tns:VaccineMatcher>
